/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2024-07-18 01:17:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class classPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/hf.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/pages/categoryPage.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/slider.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.js\"\r\n");
      out.write("        integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/6e9a783fd9.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("        <div class=\"headCategoryBar width-1280px margin-auto\">\r\n");
      out.write("        <div id=\"chosenCategory\">\r\n");
      out.write("            <div id=\"chosenCategoryButton\"><span class=\"categoryNameDetail\"></span><i class=\"fa-solid fa-angle-down\" id=\"CategoryBoxdown\"></i><i class=\"fa-solid fa-angle-up\" id=\"CategoryBoxUp\"></i></div>\r\n");
      out.write("            <div>초기화</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"chosenCategoryName\">\r\n");
      out.write("            <div><span id=\"categoryName\"></span></div>\r\n");
      out.write("            <div><span class=\"categoryNameDetail\"></span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"chosenCategoryMenu\">\r\n");
      out.write("            <div>\r\n");
      out.write("                <h2>카테고리</h2>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"scrollChosenCategoryMenuBox\">\r\n");
      out.write("                <div id=\"scrollChosenCategoryMenu\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li><label>실무·취업·자기계발<input type=\"radio\" name=\"category\" value=\"실무·취업·자기계발\"></label></li>\r\n");
      out.write("                        <li><label>데이터·개발<input type=\"radio\" name=\"category\" value=\"데이터·개발\"></label></li>\r\n");
      out.write("                        <li><label>재테크·투잡<input type=\"radio\" name=\"category\" value=\"재테크·투잡\"></label></li>\r\n");
      out.write("                        <li><label>드로잉·사진·글<input type=\"radio\" name=\"category\" value=\"드로잉·사진·글\"></label></li>\r\n");
      out.write("                        <li><label>더미 데이터<input type=\"radio\" name=\"category\" value=\"더미데이터\"></label></li>\r\n");
      out.write("                        <li><label>더미 데이터<input type=\"radio\" name=\"category\" value=\"더미데이터\"></label></li>\r\n");
      out.write("                        <li><label>더미 데이터<input type=\"radio\" name=\"category\" value=\"더미데이터\"></label></li>\r\n");
      out.write("                        <li><label>더미 데이터<input type=\"radio\" name=\"category\" value=\"더미데이터\"></label></li>\r\n");
      out.write("                        <li><label>더미 데이터<input type=\"radio\" name=\"category\" value=\"더미데이터\"></label></li>\r\n");
      out.write("                        <li><label>더미 데이터<input type=\"radio\" name=\"category\" value=\"더미데이터\"></label></li>\r\n");
      out.write("                        <li><label>더미 데이터<input type=\"radio\" name=\"category\" value=\"더미데이터\"></label></li>\r\n");
      out.write("                        <li><label>더미 데이터<input type=\"radio\" name=\"category\" value=\"더미데이터\"></label></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"chosenCategoryDetail\">\r\n");
      out.write("                    <div id=\"실무·취업·자기계발\" class=\"category\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>직무역량</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"직무역량 전체\">직무역량 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"영업·MD\">영업·MD</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"세무·회계·법률\">세무·회계·법률</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"기획·PM\">기획·PM</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"다양한 직무\">다양한 직무</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"마케팅\">마케팅</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>필수역량</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"필수역량 전체\">필수역량 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"생산성 툴\">생산성 툴</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"보고서/발표\">보고서/발표</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"엑셀\">엑셀</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"PPT\">PPT</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"직장생활·노하우\">직장생활·노하우</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>자기 계발</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"자기계발 전체\">자기계발 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"자기 관리\">자기 관리</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"인문·교양\">인문·교양</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"스피치\">스피치</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>취업·이직</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"취업·이직\">취업·이직</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"자소서·면접\">자소서·면접</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"취업/이직/진로\">취업/이직/진로</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"자격증·시험\">자격증·시험</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"데이터·개발\" class=\"category\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>개발·테크</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"개발·테크 전체\">개발·테크 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"개발 공통\">개발 공통</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"ML·AL\">ML·AL</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"모바일\">모바일</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"프론트엔드\">프론트엔드</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"백엔드\">백엔드</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"개발 입문\">개발 입문</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>데이터</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"데이터 전체\">데이터 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"데이터·일반·통계\">데이터·일반·통계</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"Python·R\">Python·R</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"SQL\">SQL</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"업무 자동화\">업무 자동화</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"재테크·투잡\" class=\"category\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>재테크</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"재테크 전체\">재테크 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"가상 자산\">가상 자산</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"금융지식\">금융지식</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"주식\">주식</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"부동산\">부동산</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>투잡·창업</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"투잡·창업 전체\">투잡·창업 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"블로그·인스타\">블로그·인스타</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"다양한 투잡\">다양한 투잡</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"쇼핑몰\">쇼핑몰</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"창업\">창업</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"드로잉·사진·글\" class=\"category\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>글쓰기</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"글쓰기 전체\">글쓰기 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"글쓰기\">글쓰기</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"출판\">출판</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>사진</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"사진 전체\">사진 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"사진\">사진</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>드로잉·미술</li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"드로잉·미술 전체\">드로잉·미술 전체</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"취미미술\">취미미술</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"디지털드로잉\">디지털드로잉</label></li>\r\n");
      out.write("                            <li><label><input type=\"radio\" name=\"categoryDetail\" value=\"캘리그래피\">캘리그래피</label></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"ChosenCategoryMenuBottom\">\r\n");
      out.write("                <div id=\"filterResetBtn\">\r\n");
      out.write("                    필터 초기화\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    필터 적용\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"contentWrapper\">\r\n");
      out.write("        <div class=\"contentBoxs\" id=\"contentSlider\">\r\n");
      out.write("            <div class=\"contentBoxsSet\" id=\"contentBoxSet\">\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"contentWrapper\">\r\n");
      out.write("        <div class=\"contentBoxs\" id=\"contentSlider\">\r\n");
      out.write("            <div class=\"contentBoxsSet\" id=\"contentBoxSet\">\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"contentWrapper\">\r\n");
      out.write("        <div class=\"contentBoxs\" id=\"contentSlider\">\r\n");
      out.write("            <div class=\"contentBoxsSet\" id=\"contentBoxSet\">\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"contentBox\">\r\n");
      out.write("                    <img\r\n");
      out.write("                        src=\"https://www.taling.me/_next/image?url=https%3A%2F%2Fimg.taling.me%2FContent%2FUploads%2FImages%2F85b0d8ca8eb43e350b84487b3fb7783d9ef84215.png&w=640&q=75\">\r\n");
      out.write("                    <div class=\"contentTitle\">50만 어쩌구</div>\r\n");
      out.write("                    <div class=\"contentAuthor\">홍길동</div>\r\n");
      out.write("                    <div class=\"contentStars\">★ (<span>3.9</span>)</div>\r\n");
      out.write("                    <div class=\"contentPrice\">160,000원</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/pages/categoryPage.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/common/slider.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/common/hf.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
