SELECT EMP_NAME, SALARY, SALARY*12 as 연봉 FROM EMPLOYEE;

select sysDATE FROM DUAL;

SELECT SYSDATE/365 FROM DUAL;
--EMPLOYEE 테이블에서
--부서코드가 'D9'DLS WLRDNJSDML
--사번, 이름, 부서코드, 전화번호 조회
SELECT * FROM EMPLOYEE;

SELECT EMP_ID, EMP_NAME, DEPT_CODE, PHONE FROM EMPLOYEE WHERE DEPT_CODE='D9';

--EMPLOYEE 테이블에서 성이 '전'씨인 사원의 사번, 이름 조회

SELECT EMP_NO, EMP_NAME FROM EMPLOYEE WHERE EMP_NAME LIKE '전%';

--EMPLOYEE 테이블에서 성이 '하'가 포함된 사원의 사번, 이름 조회

SELECT EMP_NO, EMP_NAME FROM EMPLOYEE WHERE EMP_NAME LIKE '%하%';

-- 010으로 시작하지 "않는" 사람들 조회
--> NOT LIKE (LIKE 결과 부정)

SELECT * FROM EMPLOYEE WHERE PHONE NOT LIKE '010%';

-- EMPLOYEE 테이블에서 메일 주소 '_'의 앞이 4자 이면서 DEPT_CODE가 D9 또는 D6이고
-- 고용일이 90/01/01 ~ 00/12/01이고, 급여가 270만 이상인 사원 전체를 조회

SELECT * FROM EMPLOYEE WHERE EMAIL LIKE '____$_%' ESCAPE '$' AND (DEPT_CODE = 'D9' OR DEPT_CODE = 'D6') AND HIRE_DATE BETWEEN '1990/01/01' AND '2000/12/01' AND SALARY >= 2700000;

--EMPLOYEE 테이블에서
--부서코드가 D1또는 D6또는 D9인 사원의 사번, 이름, 부서코드 조회
SELECT EMP_NO, EMP_NAME , DEPT_CODE FROM EMPLOYEE WHERE (DEPT_CODE = 'D1' OR DEPT_CODE='D6');

--12글자인 이메일만 조회
SELECT EMAIL FROM EMPLOYEE WHERE LENGTH(EMAIL)='12';

-- EMPLOYEE 테이블에서 사원명, 이메일 중 아이디만 조회
SELECT EMAIL FROM EMPLOYEE;
SELECT EMAIL ,SUBSTR(EMAIL, 1, INSTR(EMAIL, '@')-1)FROM EMPLOYEE ; 

-- 직원들의 성별 구분하기
SELECT EMP_NAME , DECODE(SUBSTR(EMP_NO, 8,1),1,'남자',2,'여자') FROM EMPLOYEE;

--EMPLOYEE 테이블에서 부서코드, 부서(그룹) 별 급여 합계 조회
SELECT * FROM EMPLOYEE;
SELECT DEPT_CODE, SUM(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE;

--EMPLOYEE 테이블에서
--성별과 성별 별 급여 평균(정수처리), 급여 합계 ,인원수 조회하고
--인원 수로 내림차순 정렬

SELECT DECODE(SUBSTR(EMP_NO, 8,1),1,'남자',2,'여자') ,AVG(SALARY), SUM(SALARY), COUNT(*) FROM EMPLOYEE GROUP BY DECODE(SUBSTR(EMP_NO, 8,1),1,'남자',2,'여자') ;

--EMPLOYEE 테이블에서 부서코드가 'D5' , 'D6'인 부서의 평균 급여 조회

SELECT DEPT_CODE, AVG(SALARY) FROM EMPLOYEE WHERE DEPT_CODE IN('D5','D6') GROUP BY DEPT_CODE;

-- 부서별 평균 급여가 3000000원 이상인 부서를 조회하여 부서코드 오름차순 정렬
SELECT DEPT_CODE, AVG(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE HAVING AVG(SALARY)>=3000000;

-- 1. EMPLOYEE 테이블에서 각 부서별 가장 높은 급여, 가장 낮은 급여를 조회하여
-- 부서 코드 오름차순으로 정렬하세요.

SELECT DEPT_CODE ,MAX(SALARY),MIN(SALARY) FROM EMPLOYEE GROUP BY DEPT_CODE ORDER BY DEPT_CODE ASC;

-- 2.EMPLOYEE 테이블에서 각 직급별 보너스를 받는 사원의 수를 조회하여
-- 직급코드 오름차순으로 정렬하세요

SELECT COUNT(BONUS) FROM EMPLOYEE GROUP BY DEPT_CODE ORDER BY DEPT_CODE;
-- 3.EMPLOYEE 테이블에서 
--  70년대생의 부서별 급여 평균이 300만 이상인 부서를 조회하여
-- 부서 코드 오름차순으로 정렬하세요
SELECT DEPT_CODE ,AVG(SALARY) FROM EMPLOYEE WHERE SUBSTR(EMP_NO,1,2) BETWEEN '70' AND '79' GROUP BY DEPT_CODE HAVING AVG(SALARY)> 3000000 ORDER BY DEPT_CODE DESC;

