--1 번
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, ENTRANCE_DATE 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO IN ('002')
ORDER BY ENTRANCE_DATE;

--2번 

SELECT PROFESSOR_NAME , PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) !=3;

--3번
SELECT PROFESSOR_NAME 교수이름,
FLOOR(MONTHS_BETWEEN( SYSDATE, TO_DATE ( 19 || SUBSTR(PROFESSOR_SSN,1,6), 'RRRR/MM/DD' ))/12 -1 ) AS 나이
FROM TB_PROFESSOR
WHERE SUBSTR(PROFESSOR_SSN, 8,1)=1
ORDER BY 2;
--??

SELECT PROFESSOR_NAME , TO_DATE (19|| SUBSTR(PROFESSOR_SSN,1,6), 'RRRR/MM/DD')
FROM TB_PROFESSOR;

--4번
SELECT SUBSTR(PROFESSOR_NAME, 2,2) 이름
FROM TB_PROFESSOR;

--5번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) -
    EXTRACT(YEAR FROM TO_DATE( 19 || SUBSTR(STUDENT_SSN,1,6), 'RRRRMMDD' )) > 19;

--6번

SELECT TO_CHAR(TO_DATE('201225', 'RRMMDD'), 'DAY')
FROM DUAL;

--7번

--TO_DATE('99/10/11', 'YY/MM/DD') 는 2099년을 의미한다
--TO_DATE('49/10/11', 'YY/MM/DD') 는 2049년을 의미한다
--TO_DATE('99/10/11', 'RR/MM/DD') 는 1999년을 의미한다
--TO_DATE('49/10/11', 'RR/MM/DD') 는 2049년을 의미한다

--8번
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1,1) != 'A';

--9번

SELECT ROUND(AVG(POINT),1)
FROM TB_GRADE G, TB_STUDENT S
WHERE G.STUDENT_NO = S.STUDENT_NO 
AND S.STUDENT_NO = 'A517178';

--10번

SELECT DEPARTMENT_NO 학과번호 , COUNT(*) 학생수
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ASC;

--11번

SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

SELECT SUBSTR(TERM_NO,1,4)
FROM TB_GRADE;

--12번

SELECT SUBSTR(TERM_NO,1,4) 년도, ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
JOIN TB_STUDENT USING(STUDENT_NO)
WHERE STUDENT_NAME = '김고운'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY SUBSTR(TERM_NO,1,4) ASC;


--13번

SELECT DEPARTMENT_NO 학과코드명 , SUM(DECODE(ABSENCE_YN,'Y',1,'N',0)) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;

SELECT DEPARTMENT_NO 학과코드명 , COUNT(DECODE(ABSENCE_YN,'Y','Y','NNNNN','N')) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;
-- SUM과 COUNT의 다른점 확인
SELECT DEPARTMENT_NO 학과코드명 , COUNT(DECODE(ABSENCE_YN,'Y','Y','NNNNN','N')) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY 1;
0 CASE로 다시 넣어서
case when cs_type=1 and cs_state=2 then 1 end


--14번

SELECT STUDENT_NAME AS "동일이름" , COUNT(STUDENT_NAME) AS "동명인 수"
FROM TB_STUDENT
HAVING COUNT(STUDENT_NAME) != 1
GROUP BY STUDENT_NAME
ORDER BY STUDENT_NAME ASC;


--15번

SELECT NVL(SUBSTR(TERM_NO,1,4),' ') 년도 , NVL(SUBSTR(TERM_NO ,5,2),' ') 학기 , ROUND(AVG(POINT),1) 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4) , SUBSTR(TERM_NO,5,2))
ORDER BY SUBSTR(TERM_NO,1,4);

