-- [관리자 계정] member 계정 생성
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
CREATE USER hgh_member IDENTIFIED BY member1234;

-- [관리자 계정] CONNECT , RESOURCE + CREATE VIEW 권한 부여 + 객체 생성 공간 할당
GRANT CONNECT, RESOURCE, CREATE VIEW TO hgh_member;
ALTER USER hgh_member DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

--hgh_member 계정 접속 방법 추가

--[멤버 계정]
CREATE TABLE MEMBER(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) NOT NULL,
    MEMBER_PW VARCHAR2(20) NOT NULL,
    MEMBER_NM VARCHAR2(30) NOT NULL,
    MEMBER_GENDER CHAR(1) CHECK(MEMBER_GENDER IN ('M','F') ),
    ENROLL_DATE DATE DEFAULT SYSDATE ,
    SECESSION_FL CHAR(1) DEFAULT 'N' CHECK(SECESSION_FL IN ('Y','N'))
);
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원 번호(PK)';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '회원 성별(M/F)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN MEMBER.SECESSION_FL IS '회원 탈퇴여부(Y/N)';

-- 게시판 테이블
CREATE TABLE BOARD(
        BOARD_NO NUMBER PRIMARY KEY,
        BOARD_TITLE VARCHAR2(200) NOT NULL,
        BOARD_CONTENT VARCHAR2(4000) NOT NULL,
        CREATE_DATE DATE DEFAULT SYSDATE,
        READ_COUNT NUMBER DEFAULT 0,
        MEMBER_NO NUMBER REFERENCES MEMBER -- MEMBER 테이블 PK값 참조
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '게시글 작성일';
COMMENT ON COLUMN BOARD.READ_COUNT IS '게시글 조회수';
COMMENT ON COLUMN BOARD.MEMBER_NO IS '회원 번호(작성자)';

-- 댓글 테이블

CREATE TABLE REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(500) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MEMBER_NO NUMBER REFERENCES MEMBER, --MEMBER 테이블 PK참조
    BOARD_NO NUMBER REFERENCES BOARD -- BOARD 테이블 PK참조
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글 번호(PK)';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글 내용';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '댓글 작성일';
COMMENT ON COLUMN REPLY.MEMBER_NO IS '회원 번호(작성자)';
COMMENT ON COLUMN REPLY.BOARD_NO IS '게시글 번호(어떤 게시글의 댓글인지 확인)';

-- 각 테이블 PK 생성용 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO; -- 1부터 1씩 증가, 반복X
CREATE SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_REPLY_NO;
---------------------------------------------------
--아이디 중복 검사
SELECT COUNT(*) FROM MEMBER
WHERE MEMBER_ID = 'user01'
AND SECESSION_FL = 'N'; --탈퇴 안한 계정

SELECT COUNT(*) FROM MEMBER WHERE MEMBER_ID='user01' AND SECESSION_FL = 'N';

--회원 가입을 위한 SQL문
SELECT * FROM MEMBER;
INSERT INTO MEMBER VALUES (SEQ_MEMBER_NO.NEXTVAL, 'USER', 'PASS', '이름', 'F', DEFAULT, DEFAULT);

COMMIT;

-- 로그인
SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, MEMBER_GENDER, ENROLL_DATE FROM MEMBER WHERE MEMBER_ID='USER' AND MEMBER_PW='PASS' AND SECESSION_FL='N';

-- 가입된 회원 목록 조회(아이디 , 이름 ,가입일)
-- 단, 탙퇴한 회원 제외, 아이디 오름 차순 조회

SELECT * FROM MEMBER WHERE SECESSION_FL = 'N' ORDER BY 'MEMBER_ID';

SELECT * FROM MEMBER;
--내 정보 수정 (이름 , 성별)
UPDATE MEMBER SET MEMBER_NM = 'user3', MEMBER_GENDER = 'F' WHERE MEMBER_NO = 3;

ROLLBACK;

--비밀번호 수정(현재 비밀번호 필요)
UPDATE MEMBER SET MEMBER_PW = '3' WHERE MEMBER_PW='5' AND MEMBER_NO = '3';
--회원 탈퇴
UPDATE MEMBER SET SECESSION_FL ='Y' WHERE SECESSION_FL='N' AND MEMBER_NO=로그인한 회원 번호 AND MEMBER_PW=로그인한 회원의 현재 비밀번호;
UPDATE MEMBER SET SECESSION_FL ='Y' WHERE SECESSION_FL='N' AND MEMBER_NO=3 AND MEMBER_PW=3;


--------------------------------------------------------------------------------

-- 게시글 목록 조회

SELECT BOARD_NO , BOARD_TITLE, CREATE_DATE , READ_COUNT, MEMBER_NM
FROM BOARD
JOIN MEMBER USING(MEMBER_NO)
ORDER BY BOARD_NO DESC;
--게시글 번호가 크다 == 최신 글이다.
SELECT * FROM BOARD;

--게시글 목록 조회 + 댓글 개수(상관 서브쿼리 + 스칼라 서브쿼리)
SELECT BOARD_NO , BOARD_TITLE, CREATE_DATE , READ_COUNT, MEMBER_NM ,
(SELECT COUNT(*)
FROM REPLY R
WHERE R.BOARD_NO= B.BOARD_NO) AS REPLY_COUNT
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
ORDER BY BOARD_NO DESC;

--댓글 개수 조회(특정 게시글만)
SELECT COUNT(*)
FROM REPLY
WHERE BOARD_NO = 3;



rollback;
INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글1', '샘플1 내용 입니다.', SYSDATE, DEFAULT, 3);

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글2', '샘플2 내용 입니다.', SYSDATE, DEFAULT, 3);

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글3', '샘플3 내용 입니다.', SYSDATE, DEFAULT, 3);
COMMIT;

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글4', '샘플4내용 입니다.', SYSDATE, DEFAULT, 3);
COMMIT;

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글5', '샘플5내용 입니다.', SYSDATE, DEFAULT, 3);
COMMIT;

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글6', '샘플6내용 입니다.', SYSDATE, DEFAULT, 6);

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글7', '샘플7내용 입니다.', SYSDATE, DEFAULT, 6);


SELECT * FROM BOARD;

--댓글 샘플 데이터 삽입
--REPLY_NO, REPLY_CONTENT, CREATE_DATE, MEMBER_NO, BOARD_NO
INSERT INTO REPLY
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플1의 댓글1', DEFAULT, 3 , 3);

INSERT INTO REPLY
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플1의 댓글2', DEFAULT, 3 , 3);

INSERT INTO REPLY
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플1의 댓글3', DEFAULT, 3 , 3);
rollback;
COMMIT;

-- 특정 게시글 상세 조회
SELECT B.* , MEMBER_NM
FROM BOARD B
JOIN MEMBER M ON B.MEMBER_NO = M.MEMBER_NO
WHERE BOARD_NO = 3;

-- 댓글 목록에서 최근에 작성한 댓글은 위or아래 아무거나
-- 특정 게시글의 댓글 목록 조회
SELECT R.* , MEMBER_NM
FROM REPLY R
JOIN MEMBER M ON (R.MEMBER_NO = M.MEMBER_NO)
WHERE BOARD_NO = '3'
ORDER BY REPLY_NO DESC; --최근 댓글 제일 상단
--ORDER BY REPLY_NO; -- 최근 댓글 하단

--게시글 조회 수 증가
-- 이전 조회수 +1
UPDATE SET READ_COUNT=READ_COUNT+1 WHERE BOARD_NO = 상세 조회한 게시글 번호;
ROLLBACK;
-- 게시글 삭제
SELECT * FROM BOARD;
SELECT * FROM REPLY;
DELETE FROM BOARD WHERE BOARD_NO=15;
--> 기본저긍로 삭제 불가
--> 삭제 옵션을 추가하면 가능
-- ON DELETE SET NULL (자식 컬럼 NULL) / ON DELETE CASCADE(참조하던 자식 행도 삭제)

-- 제약 조건은 ALTER(변경) 없음 -> 삭제 후 다시 추가
-- 기존 REPLY 테이블 FK 제약조건 삭제
ALTER TABLE REPLY DROP CONSTRAINT SYS_C008536;
 --오류 발생했던 것

-- 삭제 옵션이 추가된 FK를 다시 추가
ALTER TABLE REPLY ADD FOREIGN KEY(BOARD_NO) REFERENCES BOARD ON DELETE CASCADE;
-- 이제 삭제가 잘 된다
ROLLBACK;
COMMIT;

SELECT * FROM BOARD WHERE BOARD_NO=3;
SELECT * FROM REPLY WHERE BOARD_NO=3;


UPDATE BOARD
SET BOARD_TITLE = '66'
, BOARD_CONTENT = '66'
WHERE BOARD_NO = '18';
ROLLBACK;
SELECT * FROM BOARD;




SELECT * FROM REPLY;
ROLLBACK;
-- 댓글 수정
UPDATE REPLY SET REPLY_CONTENT = '5555555'
WHERE REPLY_NO = '5';


--댓글 삭제
DELETE FROM REPLY WHERE REPLY_NO='8';


-- 댓글 삽입
INSERT INTO REPLY
VALUES ( SEQ_REPLY_NO.NEXTVAL , '123', DEFAULT, 6, 17) );
select*from reply;

--게시글 작성
INSERT INTO BOARD VALUES(SEQ_BOARD_NO.NEXTVAL, BOARD_TITLE, BOARD_CONTENT, DEFAULT, DEFAULT, MEMBER_NO);


INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글7', '샘플7내용 입니다.', SYSDATE, DEFAULT, 6);

select * from board;

--제목 검색
SELECT * FROM BOARD WHERE BOARD_TITLE LIKE '%19%';
--게시글 검색
SELECT * FROM BOARD WHERE BOARD_TITLE LIKE '%' || ? || '%'
COMMIT;

SELECT BOARD_NO , BOARD_TITLE, CREATE_DATE , READ_COUNT, MEMBER_NM
FROM BOARD
JOIN MEMBER USING(MEMBER_NO)
--제목
WHERE BOARD_TITLE LIKE '%'||19||'%'
--내용
--WHERE BOARD_CONTENT LIKE '%'||?||'%'
--제목+내용
--WHERE BOARD_TITLE LIKE '%'||?||'%' OR BOARD_CONTENT LIKE '%' || ? || '%'
--작성자 이름
--WHERE MEMBER_NM LIKE '%' || ? || '%'
ORDER BY BOARD_NO DESC;
