/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2024-07-22 08:56:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.review;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class review_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1720687749000L));
    _jspx_dependants.put("jar:file:/C:/workspace/semiproject/talent-four/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/workspace/semiproject/talent-four/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("            <!DOCTYPE html>\r\n");
      out.write("            <html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("            <head>\r\n");
      out.write("                <meta charset=\"UTF-8\">\r\n");
      out.write("                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                <title>Review</title>\r\n");
      out.write("                <!-- css, js, header 다 넣어서 사용해주세요 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <!-- JS -->\r\n");
      out.write("                <script src=\"https://code.jquery.com/jquery-3.7.1.js\"\r\n");
      out.write("                    integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("                <script src=\"https://kit.fontawesome.com/6e9a783fd9.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("            </head>\r\n");
      out.write("\r\n");
      out.write("            <body>\r\n");
      out.write("\r\n");
      out.write("                <!-- header -->\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <main>\r\n");
      out.write("                    <div id=\"main-header\">\r\n");
      out.write("                        <div class=\"headerbtn btn1\">추천 순</div>\r\n");
      out.write("                        <div class=\"headerbtn btn2\">최신 순</div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"headerbtn btn3\">글쓰기</div>\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <div class=\"searchBox\">\r\n");
      out.write("                                <input type=\"text\" name=\"search\">\r\n");
      out.write("                                <button class=\"fa-solid fa-magnifying-glass\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"main-box\">\r\n");
      out.write("                        <div class=\"content\">\r\n");
      out.write("                            <div class=\"titlebox\">\r\n");
      out.write("                                <span class=\"title\">HAPPY 강의</span>\r\n");
      out.write("                                <div class=\"updateBtn\">수정하기</div>\r\n");
      out.write("                                <div class=\"deleteBtn\">삭제하기</div>\r\n");
      out.write("                                <span class=\"lecturer\">강사</span>\r\n");
      out.write("                                <span class=\"name\">강사명</span>\r\n");
      out.write("                                <div class=\"recommend-btn\">추천</div>\r\n");
      out.write("                                <div class=\"declaration-btn\">신고</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"classimgcontainer\">\r\n");
      out.write("                                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/class.jpg\" class=\"classimg\">\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"reviewcontentbox\">\r\n");
      out.write("                                <div class=\"reviewtitle\">\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/profile-default.jpg\" class=\"profileimg\">\r\n");
      out.write("                                    <div class=\"name1\">\r\n");
      out.write("                                        <div class=\"reviewer\">황건하(wh****)</div>\r\n");
      out.write("                                        <div class=\"reviewScore\">\r\n");
      out.write("                                            <div class=\"star\" style=\"color:gold\">★★★★★</div>\r\n");
      out.write("                                            <div class=\"starnum\">(5.0)</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"title1\">\r\n");
      out.write("                                        <div class=\"title1-reviewtitle\">초보자가 듣기에 진짜 개별로긴함</div>\r\n");
      out.write("                                        <div class=\"title1-reviewsubtitle\">\r\n");
      out.write("                                            <div class=\"title1-reviewsubtitle-date color626262\">작성일 2022.12.12</div>\r\n");
      out.write("                                            <div class=\"title1-reviewsubtitle-recommend color595959\">추천 12</div>\r\n");
      out.write("                                            <div class=\"title1-reviewsubtitle-report color595959\">신고 2</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"contentbox\">\r\n");
      out.write("                                    <div class=\"reviewcontext\">우리는 이 행동을 계속해야 합니다. 우리는 진정한 의지를 발휘하고 있으며, 우리는 최대의 성취를 이루기\r\n");
      out.write("                                        위해 최선을\r\n");
      out.write("                                        다할 것입니다. 우리는 여기에 대해 매우 흥분하고 있으며, 우리는 그것을 통해 큰 성과를 이룰 수 있을 것이라고 확신하고 있습니다. 그것은 우리\r\n");
      out.write("                                        모두에게 큰\r\n");
      out.write("                                        영감을 주는 일이 될 것입니다.\r\n");
      out.write("                                        우리는 이 행동을 계속해야 합니다. 우리는 진정한 의지를 발휘하고 있으며, 우리는 최대의 성취를 이루기 위해 최선을 다할 것입니다. 우리는\r\n");
      out.write("                                        여기에 대해 매우\r\n");
      out.write("                                        흥분하고 있으며, 우리는 그것을 통해 큰 성과를 이룰 수 있을 것이라고 확신하고 있습니다. 그것은 우리 모두에게 큰 영감을 주는 일이 될\r\n");
      out.write("                                        것입니다.\r\n");
      out.write("                                        우리는 이 행동을 계속해야 합니다. 우리는 진정한 의지를 발휘하고 있으며, 우리는 최대의 성취를 이루기 위해 최선을 다할 것입니다. 우리는\r\n");
      out.write("                                        여기에 대해 매우\r\n");
      out.write("                                        흥분하고 있으며, 우리는 그것을 통해 큰 성과를 이룰 수 있을 것이라고 확신하고 있습니다. 그것은 우리 모두에게 큰 영감을 주는 일이 될\r\n");
      out.write("                                        것입니다.\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"reviewtag\">#강사님이 친절해요</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"background-modal\" hidden></div>\r\n");
      out.write("                    <div id=\"write-modal\" hidden>\r\n");
      out.write("                        <div class=\"write-wrapper\">\r\n");
      out.write("                            <form action=\"#\">\r\n");
      out.write("                                <div class=\"write-lecture\">\r\n");
      out.write("                                    <label for=\"lecture\" class=\"selectlabel\">리뷰할 강의를 골라주세요</label>\r\n");
      out.write("                                    <select name=\"lecture\" class=\"selectBox\" required>\r\n");
      out.write("                                        <option value=\"javascript\">JavaScript</option>\r\n");
      out.write("                                        <option value=\"php\">PHP</option>\r\n");
      out.write("                                        <option value=\"java\">Java</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"write-tag\">\r\n");
      out.write("                                    <div class=\"write-tag-question\">태그를 선택해 주세요</div>\r\n");
      out.write("                                    <div class=\"write-tag-select\">\r\n");
      out.write("                                        <div class=\"radio-button selected\" data-value=\"1\">#재밌어요</div>\r\n");
      out.write("                                        <div class=\"radio-button\" data-value=\"2\">#이해하기 쉬워요</div>\r\n");
      out.write("                                        <div class=\"radio-button\" data-value=\"3\">#친절해요</div>\r\n");
      out.write("                                        <div class=\"radio-button\" data-value=\"4\">#구성이 알차요</div>\r\n");
      out.write("                                        <div class=\"radio-button\" data-value=\"5\">#생각</div>\r\n");
      out.write("                                        <div class=\"radio-button\" data-value=\"6\">#나면</div>\r\n");
      out.write("                                        <div class=\"radio-button\" data-value=\"7\">#채우기</div>\r\n");
      out.write("                                        <div class=\"radio-button\" data-value=\"8\">#다음에</div>\r\n");
      out.write("                                        <div class=\"radio-button\" data-value=\"9\">#키워드가 없어요</div>\r\n");
      out.write("                                        <input type=\"radio\" name=\"option\" value=\"1\" id=\"option1\" required checked\r\n");
      out.write("                                            hidden>\r\n");
      out.write("                                        <input type=\"radio\" name=\"option\" value=\"2\" id=\"option2\" hidden>\r\n");
      out.write("                                        <input type=\"radio\" name=\"option\" value=\"3\" id=\"option3\" hidden>\r\n");
      out.write("                                        <input type=\"radio\" name=\"option\" value=\"4\" id=\"option4\" hidden>\r\n");
      out.write("                                        <input type=\"radio\" name=\"option\" value=\"5\" id=\"option5\" hidden>\r\n");
      out.write("                                        <input type=\"radio\" name=\"option\" value=\"6\" id=\"option6\" hidden>\r\n");
      out.write("                                        <input type=\"radio\" name=\"option\" value=\"7\" id=\"option7\" hidden>\r\n");
      out.write("                                        <input type=\"radio\" name=\"option\" value=\"8\" id=\"option8\" hidden>\r\n");
      out.write("                                        <input type=\"radio\" name=\"option\" value=\"9\" id=\"option9\" hidden>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"write-content\">\r\n");
      out.write("                                    <div class=\"writestarbox\">\r\n");
      out.write("                                        <div class=\"starsel\">\r\n");
      out.write("                                            <input type=\"radio\" name=\"writestar\" value=\"5\" id=\"star1\" required\r\n");
      out.write("                                                hidden><label for=\"star1\">★ </label><input type=\"radio\" name=\"writestar\"\r\n");
      out.write("                                                value=\"4\" id=\"star2\" hidden><label for=\"star2\">★ </label><input\r\n");
      out.write("                                                type=\"radio\" name=\"writestar\" value=\"3\" id=\"star3\" hidden><label\r\n");
      out.write("                                                for=\"star3\">★ </label><input type=\"radio\" name=\"writestar\" value=\"2\"\r\n");
      out.write("                                                id=\"star4\" hidden><label for=\"star4\">★ </label><input type=\"radio\"\r\n");
      out.write("                                                name=\"writestar\" value=\"1\" id=\"star5\" hidden><label for=\"star5\">★\r\n");
      out.write("                                            </label>\r\n");
      out.write("                                            별점을 선택해주세요\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <input type=\"text\" placeholder=\"제목을 입력해주세요\" id=\"writeTitle\" name=\"writeTitle\">\r\n");
      out.write("                                        <textarea name=\"writetext\" cols=\"60\" rows=\"6\" id=\"writecontext\" maxlength=\"300\"\r\n");
      out.write("                                            placeholder=\"내용을 입력해주세요\"></textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button id=\"write-btn1\" type=\"submit\">글 쓰기</button>\r\n");
      out.write("                                    <button id=\"write-btn2\" type=\"button\">취소</button>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </main>\r\n");
      out.write("                ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("                <!-- CSS -->\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/review/review.css\">\r\n");
      out.write("                <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/common/hf.css\">\r\n");
      out.write("                <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\r\n");
      out.write("                    integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("                <script type=\"text/javascript\">\r\n");
      out.write("                    const memberNickname = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginMember.memberNickname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("                    const contextPath = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("                </script>\r\n");
      out.write("                <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/review/review.js\"></script>\r\n");
      out.write("            </body>\r\n");
      out.write("\r\n");
      out.write("            </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
